// Builds the litestream YAML config and the child-process environment.
//
// DESIGN: credentials are passed as ENVIRONMENT VARIABLES, never written into
// the YAML. The config file then contains only the database path and the
// replica URL, so it can sit on disk without being a secret, and a stray copy
// of it leaks nothing. (Litestream reads LITESTREAM_ACCESS_KEY_ID /
// LITESTREAM_SECRET_ACCESS_KEY natively; OSS_* is set too because the OSS
// backend documents those names.)
//
// The replica `url` is the whole point of this module: litestream accepts
// s3://, oss://, gs://, sftp://, webdavs://, abs://, file:// — so "where do
// backups go" is one string the operator types, not a code change.

import { DB_DIR, DATA_FILE } from "@/lib/db/paths.js";
import path from "node:path";

export const BACKUP_DIR = path.join(DB_DIR, "backup");
export const CONFIG_FILE = path.join(BACKUP_DIR, "litestream.yml");

// A backup URL must be absolute and carry a scheme litestream understands.
// Rejecting unknown schemes here is what keeps a typo ("os://") from silently
// becoming "backup is enabled but nothing is being copied".
const KNOWN_SCHEMES = ["s3:", "oss:", "gs:", "abs:", "sftp:", "webdav:", "webdavs:", "file:", "nats:"];
export const SUPPORTED_SCHEMES = KNOWN_SCHEMES.map((s) => s.replace(":", ""));

export function normalizeReplicaUrl(raw) {
  const value = String(raw ?? "").trim();
  if (!value) return "";
  const scheme = KNOWN_SCHEMES.find((s) => value.toLowerCase().startsWith(s));
  if (!scheme) {
    throw new Error(`Backup URL must start with one of: ${SUPPORTED_SCHEMES.join(", ")}`);
  }
  // file:// needs an absolute path; a relative one would resolve against the
  // process CWD and quietly write somewhere unexpected.
  if (scheme === "file:" && !/^file:\/\/\//.test(value)) {
    throw new Error("file:// backup URL must be absolute, e.g. file:///mnt/backup/spring-mouse");
  }
  return value;
}

function isOss(url) {
  return url.toLowerCase().startsWith("oss:");
}

// Minimal YAML emitter for the one shape litestream needs. Values are quoted
// defensively because a URL may contain ':' and '/' which YAML would otherwise
// reinterpret.
function quote(value) {
  return `"${String(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

export function buildConfig({ replicaUrl, databasePath = DATA_FILE }) {
  const url = normalizeReplicaUrl(replicaUrl);
  if (!url) throw new Error("A backup URL is required");
  return [
    "# Generated by Spring Mouse — do not edit by hand.",
    "# Credentials are NOT in this file; they are passed to litestream via env.",
    "dbs:",
    `  - path: ${quote(databasePath)}`,
    "    replica:",
    `      url: ${quote(url)}`,
    "",
  ].join("\n");
}

// Env for the litestream child. Merges the operator's credentials over the
// parent env so PATH etc. survive. Empty credentials are omitted rather than
// set to "" — an empty string makes some SDKs send a blank Authorization
// header, which fails with a confusing 403 instead of "no credentials".
export function buildEnv({ accessKeyId, accessKeySecret, replicaUrl, baseEnv = process.env }) {
  const env = { ...baseEnv };
  const id = String(accessKeyId ?? "").trim();
  const secret = String(accessKeySecret ?? "").trim();
  if (id) {
    env.LITESTREAM_ACCESS_KEY_ID = id;
    if (isOss(replicaUrl)) env.OSS_ACCESS_KEY_ID = id;
  }
  if (secret) {
    env.LITESTREAM_SECRET_ACCESS_KEY = secret;
    if (isOss(replicaUrl)) env.OSS_ACCESS_KEY_SECRET = secret;
  }
  // Litestream's file replica needs no credentials; leaving them unset is
  // correct there, so nothing else is added.
  return env;
}
