/**
 * Regression guard for the worker-based aggregation refactor.
 *
 * The refactor moved the aggregation body out of `usageRepo.js` into
 * `runtime/usage-aggregate.mjs` (shared by the web process and the worker). The
 * risk is that the dashboard numbers silently change.
 *
 * `__fixtures__/usage-stats-golden.json` was generated by running the
 * PRE-refactor `getUsageStats` over a fixed seed dataset. Two things make the
 * comparison stable across runs:
 *   - the seed is anchored to TODAY AT LOCAL NOON, because `requestRhythm`
 *     buckets by local hour and `byUser.periods/weekdays` follow it;
 *   - ISO timestamps and the geoip temp path are normalised.
 *
 * Periods `all` / `7d` / `24h` are compared. `today` is deliberately excluded:
 * it is defined relative to the wall clock (local midnight), so a fixture for it
 * would be meaningless an hour later.
 *
 * `getUsageStats` overlays live fields (activeRequests / recentRequests /
 * errorProvider / pending) that stay in the web process, and `last10Minutes`
 * depends on the wall clock; both are stripped before comparing.
 */
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

const HERE = path.dirname(fileURLToPath(import.meta.url));
// `all` covers every seeded row and every aggregation dimension — the strongest
// single check. `7d` adds a time-filter check; its 168h window comfortably
// contains the recent rows and excludes the 20-day-old one, so it is stable.
//
// `24h` is deliberately excluded: it is a ROLLING window (`now - 24h`) and
// getUsageStats does not accept an injected `now`, so a row seeded a fixed
// number of hours back sits on a different side of the boundary depending on
// what time of day the test runs. That is wall-clock flakiness, not a signal
// about the aggregation logic this guard protects.
const PERIODS = ["all", "7d"];

let tempDir;
const originalDataDir = process.env.DATA_DIR;

const ISO = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?Z$/;
const LIVE_FIELDS = ["activeRequests", "recentRequests", "errorProvider", "pending"];
// Bytes are totalled over a CALENDAR window (getTrafficRange: today / 24h / 7d),
// so the same seeded traffic rows fall inside or outside it depending on when
// the test runs. They are excluded from the guard for the same reason `today`
// and trafficSummary's today/week/month are: wall-clock dependent, not part of
// the aggregation contract being protected.
const CALENDAR_DEPENDENT_FIELDS = ["totalRequestBytes", "totalResponseBytes", "totalTrafficBytes"];
const TMP_GEOIP = /^.*[\\/]geoip([\\/][^\\/]+)?$/;

/** Deterministic seed anchor: today at LOCAL noon (bucket-stable). */
function seedAnchor() {
  const d = new Date();
  d.setHours(12, 0, 0, 0);
  return d.getTime();
}

/** Drop live fields + normalise timestamps/paths, mirroring the generator. */
function normalize(stats) {
  const walk = (value) => {
    if (Array.isArray(value)) return value.map(walk);
    if (value && typeof value === "object") {
      const out = {};
      for (const [k, v] of Object.entries(value)) {
        if (LIVE_FIELDS.includes(k) || k === "last10Minutes") continue;
        if (CALENDAR_DEPENDENT_FIELDS.includes(k)) continue;
        // trafficSummary.today/week/month are calendar windows (local midnight,
        // Monday, 1st of month). They legitimately change when the fixture is
        // compared on a later day, so they are not part of the aggregation
        // contract this guard protects. `recent` is a fixed-size tail and stays.
        if (k === "trafficSummary" && v && typeof v === "object") {
          out[k] = { recent: walk(v.recent) };
          continue;
        }
        out[k] = walk(v);
      }
      return out;
    }
    if (typeof value === "string") {
      if (ISO.test(value)) return "<TS>";
      if (TMP_GEOIP.test(value)) return value.replace(/^.*[\\/]geoip/, "<TMPDIR>/geoip");
    }
    return value;
  };
  return walk(stats);
}

function goldenFixture() {
  return JSON.parse(fs.readFileSync(path.join(HERE, "..", "__fixtures__", "usage-stats-golden.json"), "utf-8"));
}

beforeEach(() => {
  tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "spring-mouse-usage-agg-"));
  process.env.DATA_DIR = tempDir;
  delete global._dbAdapter;
  // Module-level caches are bound on `global` to survive Next.js hot reloads, so
  // vi.resetModules() alone does not drop them.
  delete global._usageStatsCache;
  delete global._statsEmitter;
  delete global._statsEmitTimers;
  delete global._pendingRequests;
  delete global._pendingTimers;
  delete global._recentRing;
  delete global._connectionMapCache;
  delete global._apiKeyMapCache;
  delete global._lastErrorProvider;
  delete global._smUsageAggregatePool;
  vi.resetModules();
});

afterEach(() => {
  try { global._dbAdapter?.instance?.close?.(); } catch {}
  delete global._dbAdapter;
  fs.rmSync(tempDir, { recursive: true, force: true });
  if (originalDataDir === undefined) delete process.env.DATA_DIR;
  else process.env.DATA_DIR = originalDataDir;
});

/** Must match the dataset used to generate the golden fixture, exactly. */
async function seed(db) {
  const anchor = seedAnchor();
  const iso = (offsetMs) => new Date(anchor + offsetMs).toISOString();
  const rows = [
    { t: -2, provider: "codex", model: "gpt-5", conn: "conn-a", key: "local-no-key", pt: 100, ct: 50, cost: 0.01, status: "success", ip: "1.1.1.1", geo: "JP", app: "Cursor", cached: 20 },
    { t: -3, provider: "codex", model: "gpt-5", conn: "conn-a", key: "local-no-key", pt: 200, ct: 80, cost: 0.02, status: "error", ip: "1.1.1.1", geo: "JP", app: "Cursor", cached: 0 },
    { t: -4, provider: "codex", model: "gpt-5", conn: "conn-b", key: "key-alpha", pt: 300, ct: 120, cost: 0.03, status: "success", ip: "2.2.2.2", geo: "US", app: "claude code", cached: 40 },
    { t: -5, provider: "deepseek", model: "ds-chat", conn: "conn-b", key: "key-alpha", pt: 400, ct: 160, cost: 0.04, status: "cancelled", ip: "2.2.2.2", geo: "US", app: "curl", cached: 0 },
    { t: -6, provider: "deepseek", model: "ds-chat", conn: "conn-c", key: "key-beta", pt: 500, ct: 200, cost: 0.05, status: "success", ip: null, geo: null, app: null, cached: 60 },
    { t: -480, provider: "glm", model: "glm-5", conn: "conn-c", key: "key-beta", pt: 600, ct: 240, cost: 0.06, status: "success", ip: "3.3.3.3", geo: "CN", app: "Cline", cached: 0 },
    { t: -26, provider: "glm", model: "glm-5", conn: "conn-a", key: "key-alpha", pt: 10, ct: 5, cost: 0.001, status: "success", ip: "4.4.4.4", geo: "SG", app: "Aider", cached: 0 },
  ];

  for (let i = 0; i < rows.length; i++) {
    const r = rows[i];
    const tokens = { prompt_tokens: r.pt, completion_tokens: r.ct };
    if (r.cached) tokens.cached_tokens = r.cached;
    db.run(
      `INSERT INTO usageHistory(timestamp, provider, model, connectionId, apiKeyId, requestId, startedAt, completedAt,
                                endpoint, promptTokens, completionTokens, cost, status, tokens, meta)
       VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        iso(r.t * 3600e3), r.provider, r.model, r.conn, r.key, `agg-${i}`,
        iso(r.t * 3600e3 - 1000), iso(r.t * 3600e3),
        i % 2 === 0 ? "/v1/chat/completions" : "/v1/messages",
        r.pt, r.ct, r.cost, r.status, JSON.stringify(tokens),
        JSON.stringify({ sourceIp: r.ip, sourceGeo: r.geo, appName: r.app }),
      ],
    );
  }

  for (let i = 0; i < 3; i++) {
    db.run(
      `INSERT INTO networkTraffic(requestId, timestamp, completedAt, method, endpoint, statusCode, requestBytes, responseBytes, durationMs, aborted, meta)
       VALUES(?, ?, ?, 'POST', '/v1/chat/completions', 200, ?, ?, 10, 0, ?)`,
      [`traffic-${i}`, iso(-i * 3600e3), iso(-i * 3600e3), 100 * (i + 1), 200 * (i + 1), JSON.stringify({ appName: "Cursor" })],
    );
  }
  db.run(`UPDATE usageHistory SET trafficRequestId = 'traffic-0' WHERE requestId = 'agg-0'`);
  db.run(
    `INSERT INTO apiKeys(id, key, name, isActive, createdAt) VALUES('key-alpha', 'sk-alpha-secret', 'Alpha Key', 1, ?)`,
    [iso(-30 * 24 * 3600e3)],
  );
}

async function seededStats() {
  const { getAdapter } = await import("../../src/lib/db/driver.js");
  const db = await getAdapter();
  await seed(db);
  const { getUsageStats } = await import("../../src/lib/db/repos/usageRepo.js");
  const out = {};
  for (const period of PERIODS) out[period] = normalize(await getUsageStats(period));
  return out;
}

describe("usage aggregation regression guard", () => {
  it("matches the pre-refactor golden fixture for every period", async () => {
    const golden = goldenFixture();
    const actual = await seededStats();
    for (const period of PERIODS) {
      expect(actual[period], `period=${period}`).toEqual(golden[period]);
    }
  });

  it("keeps session metrics that a day-grain rollup could not reproduce", async () => {
    const stats = (await seededStats()).all;
    const people = Object.values(stats.byUser);
    expect(people.length).toBeGreaterThan(0);
    for (const person of people) {
      expect(person).toEqual(expect.objectContaining({
        sessionCount: expect.any(Number),
        activeDays: expect.any(Number),
        periods: expect.any(Array),
        weekdays: expect.any(Array),
      }));
    }
  });

  it("scopes by apiKeyId and masks key names in byApiKey", async () => {
    const { getAdapter } = await import("../../src/lib/db/driver.js");
    const { getUsageStats } = await import("../../src/lib/db/repos/usageRepo.js");
    const db = await getAdapter();
    await seed(db);

    const scoped = normalize(await getUsageStats("all", { apiKeyId: "key-alpha" }));
    // key-alpha owns rows agg-2, agg-3, agg-6
    expect(scoped.totalRequests).toBe(3);
    expect(scoped.byUser["key-alpha"].requests).toBe(3);
    // a known key resolves its display name; the bucket still carries the mask field
    const entries = Object.values(scoped.byApiKey);
    expect(entries.length).toBeGreaterThan(0);
    for (const entry of entries) expect("apiKeyMasked" in entry).toBe(true);
  });
});
